// ===============================================================
// TITT'S QUESTIONABLE CHARACTER DESIGN BRIEF
// EDITABLE RESULT DATABASE
// ===============================================================
//
// HOW TO ADD A NEW RESULT:
//
// 1. Find the category you want below.
// 2. Add a new quoted line inside its [ square brackets ].
// 3. Put a comma after the previous result.
//
// Example:
//
//   size: [
//     "Tiny",
//     "Average",
//     "Absolutely enormous",
//     "Your new result here"
//   ],
//
// Keep the quote marks around every result.
// Do not delete the square brackets or the category name.
//
// ===============================================================

const DATA = {
  // ============================================================
  // BASE FORM
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  baseForm: [
    "Humanoid",
    "Furry",
    "Beastfolk",
    "Elf-ish",
    "Goblin-ish",
    "Giant",
    "Tiny humanoid",
    "Fairy",
    "Demon",
    "Angel",
    "Undead",
    "Vampire",
    "Were-creature",
    "Aquatic humanoid",
    "Reptilian humanoid",
    "Avian humanoid",
    "Insectoid",
    "Amphibian",
    "Plant person",
    "Mushroom person",
    "Construct",
    "Elemental",
    "Eldritch being",
    "Shapeshifter",
    "Garden gnome",
    "Porcelain doll",
    "Wooden puppet",
    "Marionette",
    "Rag doll",
    "Living statue",
    "Animated armour",
    "Haunted suit of armour",
    "Scarecrow",
    "Mannequin",
    "Clockwork toy",
    "Music box ballerina",
    "Gargoyle",
    "Snowman",
    "Candle",
    "Candelabra",
    "Teapot",
    "Kettle",
    "Vase",
    "Grandfather clock",
    "Mirror",
    "Chandelier",
    "Wardrobe",
    "Suitcase",
    "Book",
    "Painting",
    "Stained-glass window",
    "Church bell",
    "Street lamp",
    "Umbrella",
    "Sword",
    "Shield",
    "Potted plant",
    "Massive tree",
    "Bonsai tree",
    "Rose bush",
    "Sunflower",
    "Venus flytrap",
    "Cactus",
    "Mushroom",
    "Moss-covered log",
    "Walking hedge",
    "Bouquet of flowers",
    "Patch of weeds",
    "Sentient vegetable",
    "Pumpkin",
    "Onion",
    "Potato",
    "Suspiciously large courgette",
    "Jelly on a plate",
    "Sentient pudding",
    "Walking cake",
    "Gingerbread person",
    "Loaf of bread",
    "Croissant",
    "Wheel of cheese",
    "Bowl of soup",
    "Giant ravioli",
    "Sentient spaghetti",
    "Fried egg",
    "Meatball",
    "Birthday cake",
    "Mouldy sandwich",
    "A single baked bean",
    "Slime",
    "Ooze",
    "Cloud",
    "Living shadow",
    "Living flame",
    "Sentient puddle",
    "Ball of light",
    "Ball of darkness",
    "Floating eyeball",
    "Giant mouth",
    "Disembodied hands",
    "Biblically questionable angel",
    "Geometrically impossible being",
    "Walking constellation",
    "Living galaxy",
    "A hole in reality",
    "A concept given flesh",
    "A pile of bones with ambitions",
    "Several creatures pretending to be one creature",
    "Something under a sheet",
    "Nobody knows, including the artist",
    "Cat",
    "Dog",
    "Fox",
    "Wolf",
    "Rabbit",
    "Hare",
    "Rat",
    "Mouse",
    "Bat",
    "Goat",
    "Sheep",
    "Cow",
    "Horse",
    "Deer",
    "Pig",
    "Bear",
    "Raccoon",
    "Opossum",
    "Capybara",
    "Otter",
    "Seal",
    "Frog",
    "Toad",
    "Gecko",
    "Crocodile",
    "Snake",
    "Axolotl",
    "Shark",
    "Goldfish",
    "Octopus",
    "Crab",
    "Moth",
    "Bee",
    "Beetle",
    "Spider",
    "Centipede",
    "Pigeon",
    "Crow",
    "Owl",
    "Chicken",
    "Goose",
    "Peacock"
  ],

  // ============================================================
  // SIZE
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  size: [
    "Fits in your palm",
    "Handbag sized",
    "House-cat sized",
    "Knee height",
    "Child sized",
    "Short",
    "Average",
    "Tall",
    "Very tall",
    "Basketball-player tall",
    "Doorframe hazard",
    "Absolutely enormous",
    "Horse sized",
    "Car sized",
    "Elephant sized",
    "Cottage sized",
    "House sized",
    "Cathedral sized",
    "Kaiju",
    "Mountain sized",
    "Technically a geographical feature",
    "Changes size depending on mood",
    "Appears differently sized to everyone",
    "Much smaller than their personality suggests",
    "Much larger than anybody expected",
    "Exactly 3 feet tall and furious about it"
  ],

  // ============================================================
  // HOW MANY EYES?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  eyes: [
    "No eyes",
    "1 enormous central eye",
    "1 tiny eye in an otherwise featureless face",
    "2 normally positioned eyes",
    "2 eyes positioned vertically",
    "2 eyes dramatically far apart",
    "2 eyes placed low on the cheeks",
    "2 eyes placed near the temples",
    "3 eyes, with one centred on the forehead",
    "3 eyes arranged vertically",
    "3 completely asymmetrical eyes",
    "3 eyes with one much larger than the others",
    "4 eyes arranged in two neat pairs",
    "4 eyes clustered like a spider",
    "4 eyes arranged around the head",
    "4 eyes with the lower pair much smaller",
    "5 eyes forming a star-like arrangement",
    "5 eyes scattered asymmetrically across the face",
    "6 eyes in three pairs",
    "6 eyes scattered asymmetrically across the face",
    "6 eyes running down the sides of the neck",
    "8 spider-like eyes",
    "8 eyes running down the neck",
    "8 eyes spread across the shoulders",
    "8 tiny eyes circling one large eye",
    "10 tiny eyes surrounding two larger ones",
    "12 eyes scattered across the body",
    "12 eyes arranged in two vertical rows",
    "20 tiny eyes covering the face",
    "Dozens of eyes embedded in the skin",
    "Dozens of eyes running down both arms",
    "Dozens of eyes hidden between feathers",
    "Hundreds of tiny eyes forming a pattern",
    "Too many eyes to reasonably draw",
    "An uncertain number of eyes floating around the head",
    "Several eyes floating around the shoulders like jewellery",
    "One normal pair plus tiny eyes in both palms",
    "One normal pair plus an eye in the centre of the chest",
    "Eyes only on one side of the body",
    "All eyes positioned along a single curved line",
    "Eyes arranged like a constellation across the face",
    "Eyes clustered around the mouth",
    "Eyes hidden in the hair",
    "Eyes running down the tail",
    "An amount of eyes that somehow changes when counted"
  ],

  // ============================================================
  // HOW MANY ARMS?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  arms: [
    "0 arms",
    "1 arm, attached normally",
    "1 enormous arm in the centre of the chest",
    "1 arm growing from the upper back",
    "1 arm floating beside the body",
    "1 tiny arm growing from the shoulder",
    "2 arms, attached normally",
    "2 arms, both on the same side",
    "2 arms growing from the back",
    "2 arms floating beside the shoulders",
    "2 arms attached low on the torso",
    "2 arms attached high near the neck",
    "2 arms with one dramatically larger than the other",
    "2 arms joined together at the elbow",
    "3 arms, two normal and one beneath them",
    "3 arms arranged asymmetrically",
    "3 arms, with one growing from the back",
    "3 arms floating around the torso",
    "3 arms, all different sizes",
    "4 arms, stacked in two pairs",
    "4 arms arranged around the ribcage",
    "4 arms, with two normal and two growing from the back",
    "4 arms, all on one side",
    "4 arms, all floating around the body",
    "4 arms, one enormous pair and one tiny pair",
    "4 arms radiating from the shoulders",
    "4 arms with one pair mechanical and one pair organic",
    "4 arms attached around the waist",
    "5 arms arranged like a fan",
    "5 arms, all asymmetrical",
    "6 arms arranged symmetrically down the torso",
    "6 arms radiating from the shoulders",
    "6 arms, all different sizes",
    "6 arms floating behind them like a halo",
    "6 arms branching like tree limbs",
    "6 arms arranged in three stacked pairs",
    "8 arms arranged like spider limbs",
    "8 arms radiating from the back",
    "8 arms floating independently around the body",
    "8 arms attached in a ring around the torso",
    "8 arms, becoming smaller toward the hips",
    "10 tiny arms arranged around the waist",
    "10 arms fanning out behind the body",
    "12 arms, becoming progressively smaller down the torso",
    "12 arms arranged symmetrically like a many-limbed idol",
    "20 arms forming a fan behind the body",
    "Far too many arms, clustered wherever the artist can fit them",
    "Far too many arms, all floating and apparently functional",
    "An unclear number of arms emerging from shadow",
    "Several arms visible only as silhouettes behind the body"
  ],

  // ============================================================
  // HOW MANY LEGS?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  legs: [
    "0 legs, they float",
    "0 legs, serpentine lower body",
    "0 legs, just a suspicious amount of tentacles",
    "0 legs, roots trail from the lower body instead",
    "0 legs, the body ends in a cloud",
    "1 enormous central leg",
    "1 leg and apparently that's enough",
    "1 leg with a hoof",
    "1 leg floating beneath the torso",
    "2 normally positioned legs",
    "2 digitigrade legs",
    "2 enormous bird-like legs",
    "2 legs floating beneath the torso",
    "2 legs attached asymmetrically",
    "2 legs with one much longer than the other",
    "2 legs ending in completely different feet",
    "3 legs arranged like a tripod",
    "3 completely asymmetrical legs",
    "3 legs radiating from the hips",
    "4 legs in a quadruped arrangement",
    "4 legs in a centaur-like arrangement",
    "4 legs radiating from the hips",
    "4 legs, with one pair significantly smaller",
    "4 legs arranged like an insect",
    "4 legs floating beneath the body",
    "5 legs arranged like a star",
    "6 insect-like legs",
    "6 legs arranged around the lower torso",
    "6 completely different legs",
    "6 legs radiating from a spherical lower body",
    "8 spider-like legs",
    "8 legs radiating around the body",
    "8 legs floating beneath them",
    "8 legs arranged in two uneven rows",
    "10 tiny legs",
    "10 legs arranged like the spokes of a wheel",
    "12 legs becoming progressively smaller",
    "12 legs arranged symmetrically beneath a wide body",
    "Centipede quantities of tiny legs",
    "Far too many legs arranged like the spokes of a wheel",
    "Far too many legs clustered beneath the torso",
    "Anatomically inexplicable but apparently functional legs",
    "Several legs growing from the back and curving downward",
    "A lower body made of interlocking legs",
    "Legs that float separately but move in perfect sync"
  ],

  // ============================================================
  // HANDS & FEET SITUATION
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  handsFeet: [
    "Completely normal",
    "Human hands, human feet",
    "Paws",
    "Claws",
    "Talons",
    "Hooves",
    "Split hooves",
    "Bird feet",
    "Webbed hands and feet",
    "Frog fingers",
    "Gecko pads",
    "Monkey-like feet",
    "Hands instead of feet",
    "Feet instead of hands",
    "Four-fingered hands",
    "Three-fingered hands",
    "Two enormous fingers",
    "Tiny delicate hands",
    "Comically large hands",
    "Skeleton hands",
    "Mechanical hands",
    "Wooden hands",
    "Porcelain hands",
    "Tentacle fingertips",
    "Crab claws",
    "Lobster claws",
    "Praying-mantis arms",
    "Mole digging claws",
    "Bear paws",
    "Raccoon hands",
    "Opposable toes",
    "No hands, just vibes",
    "Every finger is a tiny hand"
  ],

  // ============================================================
  // TAIL SITUATION
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  tail: [
    "No tail",
    "Tiny nub",
    "Short tail",
    "Long tail",
    "Extremely long tail",
    "Fluffy tail",
    "Enormous fluffy tail",
    "Cat tail",
    "Dog tail",
    "Fox tail",
    "Wolf tail",
    "Rat tail",
    "Cow tail",
    "Horse tail",
    "Pig corkscrew tail",
    "Lizard tail",
    "Crocodile tail",
    "Snake tail",
    "Fish tail",
    "Shark tail",
    "Beaver tail",
    "Peacock tail",
    "Scorpion tail",
    "Devil tail",
    "Dragon tail",
    "Prehensile tail",
    "Armoured tail",
    "Clubbed tail",
    "Bladed tail",
    "Feathered tail",
    "Flowering tail",
    "Skeletal tail",
    "Mechanical tail",
    "Tentacle tail",
    "Tail with a hand on the end",
    "Tail with a mouth on the end",
    "Tail with an eye on the end",
    "Two tails",
    "Three tails",
    "Nine tails",
    "A concerning number of tails",
    "Tail is larger than the character",
    "Tail has its own personality",
    "They insist it isn't a tail"
  ],

  // ============================================================
  // SKIN SITUATION
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  skin: [
    "Human-like skin",
    "Very freckled",
    "Vitiligo",
    "Scales",
    "Tiny scales",
    "Huge armour-like scales",
    "Fish scales",
    "Snake scales",
    "Iridescent scales",
    "Feathers",
    "Downy feathers",
    "Peacock feathers",
    "Fur",
    "Very fluffy fur",
    "Patchy fur",
    "Velvet-like fur",
    "Frog skin",
    "Shark-like skin",
    "Blubber",
    "Chitin",
    "Beetle shell",
    "Bark",
    "Moss",
    "Leaves",
    "Flowers",
    "Mushrooms",
    "Vines",
    "Stone",
    "Marble",
    "Cracked stone",
    "Porcelain",
    "Ceramic",
    "Wood",
    "Metal",
    "Rusted metal",
    "Glass",
    "Stained glass",
    "Crystal",
    "Jelly",
    "Slime",
    "Wax",
    "Smoke",
    "Flame",
    "Water",
    "Clouds",
    "Shadow",
    "Living darkness",
    "Stars",
    "Looks like outer space",
    "Translucent",
    "Transparent",
    "Glowing",
    "Bioluminescent",
    "Covered in eyes",
    "Covered in tiny mouths",
    "Changes texture when embarrassed",
    "Looks wet. Isn't."
  ],

  // ============================================================
  // HORNS, WINGS & TEETH?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  extras: [
    "No horns, no wings, normal teeth",
    "2 tiny horns and small fangs",
    "1 enormous horn growing from the forehead",
    "1 broken horn and otherwise normal teeth",
    "2 huge ram horns and blunt herbivore teeth",
    "2 tiny horns, no wings, shark teeth",
    "4 horns framing the face",
    "4 tiny horns around the forehead and small fangs",
    "6 horns growing asymmetrically around the head",
    "A crown of tiny horns and one gold fang",
    "Antlers with small fangs",
    "One antler, no explanation",
    "Branching antlers and normal teeth",
    "Horns growing from the jawline and tiny fangs",
    "Horns growing from the shoulders instead of the head",
    "2 tiny decorative wings behind the ears",
    "2 enormous feathered wings from the back",
    "2 bat wings growing from the hips",
    "2 dragon wings that are far too large for the body",
    "2 tiny useless wings and enormous tusks",
    "4 feathered wings arranged in two pairs",
    "4 insect wings growing from the back",
    "4 mismatched wings, no horns, small fangs",
    "6 wings forming a halo-like silhouette",
    "6 tiny wings scattered across the back",
    "Tiny wings on the ankles and tiny horns",
    "One enormous wing and one tiny wing",
    "Several mismatched wings",
    "Wings that completely dwarf the body",
    "Normal teeth except for two enormous fangs",
    "Shark-like rows of teeth",
    "Huge rodent incisors",
    "Tusks curling upwards",
    "Tusks curling downwards",
    "Teeth extending slightly beyond the lips",
    "Far too many teeth for the available mouth",
    "No teeth, enormous horns",
    "No teeth, tiny butterfly wings",
    "One gold tooth and one broken horn",
    "Horns along the jaw + moth wings + tiny fangs",
    "Antlers + butterfly wings + shark teeth",
    "Tiny horns + enormous wings + no teeth",
    "Six horns + six wings + six fangs",
    "Goat horns + bat wings + blunt teeth",
    "Deer antlers + feathered wings + vampire fangs",
    "One unicorn horn + tiny fairy wings + rodent teeth",
    "Four horns + no wings + tusks",
    "No horns + six wings + shark teeth",
    "Horns growing from the spine + tiny fangs",
    "Wing-like fins instead of wings + antlers",
    "A ring of tiny horns around the neck + normal teeth",
    "Yes to all three. Excessively."
  ],

  // ============================================================
  // FASHION STYLE
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  fashion: [
    "Practical adventurer",
    "Medieval peasant",
    "Fantasy aristocrat",
    "Royal courtwear",
    "Romantic Gothic",
    "Gothic mourning",
    "Dark academia",
    "Light academia",
    "Cottagecore",
    "Fairycore",
    "Goblincore",
    "Punk",
    "Cyberpunk",
    "Steampunk",
    "Rococo",
    "Baroque",
    "Renaissance",
    "Ancient Greek drapery",
    "Viking-inspired",
    "Pirate",
    "Cowboy",
    "Witchy",
    "Wizard robes",
    "Military uniform",
    "Clerical vestments",
    "Streetwear",
    "Techwear",
    "Haute couture",
    "Avant-garde runway",
    "Corporate goth",
    "Disco",
    "Glam rock",
    "1980s aerobics",
    "1990s grunge",
    "Y2K",
    "Pastel Lolita",
    "Decora",
    "Circus performer",
    "Ringmaster",
    "Ballet",
    "Cabaret",
    "Drag",
    "Completely overdressed",
    "Completely underdressed",
    "Nudist who conceded to a loincloth",
    "Armour with an evening gown",
    "Pyjamas",
    "Dressing gown and slippers",
    "Wearing a bedsheet as a toga",
    "Everything has pockets",
    "Seventeen belts",
    "Nothing but jewellery",
    "Whatever was on the bedroom floor"
  ],

  // ============================================================
  // ACCESSORIES
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  accessories: [
    "None",
    "Sensible backpack",
    "Tiny handbag",
    "Enormous handbag",
    "Satchel",
    "Utility belt",
    "Seventeen belts",
    "Spectacles",
    "Tiny spectacles",
    "Monocle",
    "Sunglasses",
    "Goggles",
    "Eyepatch",
    "Veil",
    "Mask",
    "Half-mask",
    "Crown",
    "Tiny crown",
    "Tiara",
    "Flower crown",
    "Huge hat",
    "Tiny hat",
    "Witch hat",
    "Cowboy hat",
    "Jewellery everywhere",
    "Too many rings",
    "Huge earrings",
    "Nose chain",
    "Body chains",
    "Bells",
    "Ribbons",
    "Bows",
    "Flowers",
    "Feathers",
    "Bones",
    "Teeth",
    "Crystals",
    "Potion bottles",
    "Tiny spoons",
    "Keys",
    "Charms",
    "Pocket watch",
    "Parasol",
    "Walking stick",
    "Fan",
    "Pipe",
    "Magnifying glass",
    "A frog sitting on their head",
    "Pet mouse in a pocket",
    "Live snake worn as jewellery",
    "Shoulder pigeon",
    "Emotional-support chicken",
    "A handbag that might be alive"
  ],

  // ============================================================
  // PERSONALITY VIBE
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  personality: [
    "Golden retriever",
    "Black cat",
    "Orange cat",
    "Wet cat",
    "Chihuahua",
    "Capybara",
    "Raccoon with a credit card",
    "Opossum under pressure",
    "Goose choosing violence",
    "Crow that knows your secrets",
    "Excitable puppy",
    "Tired dad",
    "Wine aunt",
    "Theatre kid",
    "Exhausted retail worker",
    "Gentle giant",
    "Tiny ball of rage",
    "Cinnamon roll",
    "Himbo",
    "Chaos gremlin",
    "Stoic protector",
    "Hopeless romantic",
    "Flirtatious menace",
    "Polite menace",
    "Smug bastard",
    "Sunshine incarnate",
    "Human thundercloud",
    "Victorian child",
    "Victorian ghost",
    "Friendly cryptid",
    "Feral cryptid",
    "Princess",
    "Goblin princess",
    "Retired drag queen",
    "Mad scientist",
    "Sleep-deprived academic",
    "Customer-service voice concealing murderous rage",
    "Looks terrifying, wants a cuddle",
    "Looks adorable, absolutely bites",
    "Mum friend",
    "Bad influence",
    "Eldest daughter energy",
    "Has never experienced consequences",
    "Knows exactly what they're doing",
    "Has absolutely no idea what they're doing",
    "A pigeon with an appointment"
  ],

  // ============================================================
  // HOW ATTRACTIVE ARE THEY SUPPOSED TO BE?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  attractiveness: [
    "Actively hideous",
    "Creature only a mother could love",
    "Ugly-cute",
    "Weirdly adorable",
    "Unconventionally attractive",
    "Average",
    "Cute",
    "Pretty",
    "Handsome",
    "Beautiful",
    "Striking",
    "Very attractive",
    "Distractingly attractive",
    "Painfully attractive",
    "Suspiciously attractive",
    "Villainously attractive",
    "Ethereally beautiful",
    "Intimidatingly beautiful",
    "Looks expensive",
    "Looks like they smell amazing",
    "Illegal cheekbones",
    "Could ruin your life",
    "Definitely will ruin your life",
    "Tumblr would have been unbearable about them",
    "The internet is going to be weird about this one",
    "The artist accidentally made them hot"
  ],

  // ============================================================
  // WOULD THEY BE THE LEAD IN A ROMANTASY?
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  romantasy: [
    "Absolutely not. Background NPC energy.",
    "No. Lovable comic relief.",
    "No, but Tumblr will inexplicably adore them.",
    "The protagonist's attractive best friend.",
    "Secondary love-interest energy.",
    "Looks like the safe romantic option.",
    "Looks like the person you're supposed to choose.",
    "Mysterious stranger at the masquerade.",
    "Definitely the rival.",
    "Villain with suspiciously good cheekbones.",
    "Morally grey and dressed accordingly.",
    "Brooding in a doorway material.",
    "Needs a billowing shirt immediately.",
    "Needs to be leaning against something seductively.",
    "Looks permanently backlit.",
    "Hair designed specifically to blow in the wind.",
    "Immaculate jawline, questionable morals.",
    "Tall, dark and narratively concerning.",
    "Beautiful enough that everyone ignores the red flags.",
    "Looks like they own a castle with serious structural problems.",
    "Looks like they haven't smiled since Chapter Three.",
    "Definitely appears shirtless by Chapter Twelve.",
    "Someone is going to describe their eyes for an entire paragraph.",
    "Enemies-to-lovers silhouette.",
    "Monster-romance material.",
    "The monster is the love interest.",
    "Tragically beautiful.",
    "Ethereal and emotionally unavailable.",
    "Could absolutely carry someone through a burning castle.",
    "Yes. Give them an unnecessarily dramatic coat.",
    "Yes. Put them on the cover.",
    "Aggressively yes.",
    "The artist is legally required to give them bedroom eyes."
  ],

  // ============================================================
  // FINAL QUESTIONABLE DETAIL
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  finalDetail: [
    "One horn is broken",
    "One horn is dramatically larger than the other",
    "One horn curls around an ear",
    "Horns have jewellery hanging from them",
    "Horns have been painted",
    "One antler has flowers growing from it",
    "Gold caps on the tips of their horns",
    "One ear is noticeably floppy",
    "One ear has a bite missing from it",
    "One ear is covered in piercings",
    "Ears are absurdly oversized",
    "Ears are ridiculously tiny",
    "One eye is a different colour",
    "One eye is completely black",
    "One eye is completely white",
    "One eye is replaced with a gemstone",
    "One eye is replaced with a flower",
    "One eye has a star-shaped pupil",
    "Pupils are heart-shaped",
    "Pupils are horizontal like a goat's",
    "Pupils are ridiculously large",
    "Permanent dark circles under the eyes",
    "One eyebrow is shaved",
    "No eyebrows whatsoever",
    "One eyebrow is dramatically longer than the other",
    "Freckles form little constellations",
    "Freckles cover their entire body",
    "Beauty marks arranged suspiciously symmetrically",
    "A huge birthmark across half the face",
    "A heart-shaped birthmark",
    "A hand-shaped birthmark",
    "A large facial scar",
    "Scar straight through one eyebrow",
    "Several tiny scars across the nose",
    "Gold-filled scars",
    "Glowing scars",
    "Stitches visible across the body",
    "One cheek is cracked like porcelain",
    "Their entire face is cracked like an old statue",
    "One half of their face has a completely different texture",
    "Their face is perfectly symmetrical. Too symmetrical.",
    "Nose has clearly been broken several times",
    "Huge hooked nose",
    "Tiny button nose",
    "One enormous front tooth",
    "Noticeable tooth gap",
    "Gold fang",
    "One fang is broken",
    "Tusks decorated with jewellery",
    "Teeth visible even when the mouth is closed",
    "Mouth is slightly too wide",
    "Mouth extends almost to the ears",
    "Second tiny mouth somewhere on the face",
    "A mouth in the palm of one hand",
    "A single tiny eye on their forehead",
    "Tiny extra eyes beneath the normal ones",
    "An eye hidden in the centre of their chest",
    "Extra face on the back of their head",
    "Face is partially covered by feathers",
    "Face is partially covered by scales",
    "Fur only grows on one half of the body",
    "A mane running down the entire spine",
    "A ridge of feathers running down the spine",
    "Mushrooms growing from one shoulder",
    "Flowers growing directly from their hair",
    "Moss growing across their shoulders",
    "Small branches growing from their head",
    "Vines wrapped naturally around one arm",
    "One arm is made of wood",
    "One arm is skeletal",
    "One arm is translucent",
    "One arm is considerably larger than the other",
    "One hand is permanently enormous",
    "Fingertips fade into a different colour",
    "Claws are ridiculously long",
    "Claws are painted",
    "Gold claws",
    "One finger is missing",
    "Extra thumb",
    "Six fingers on each hand",
    "Hands fade into black at the fingertips",
    "One leg is digitigrade, the other isn't",
    "One leg is visibly mechanical",
    "One foot is a hoof, the other isn't",
    "Knees have small horns",
    "Elbows have feathers",
    "Shoulders have spikes",
    "Small wings growing from the ankles",
    "Tiny wings growing from the head",
    "Tiny decorative wings where ears should be",
    "Wings have jewellery threaded through them",
    "One wing is damaged",
    "One wing is dramatically smaller",
    "Wings are mismatched species",
    "Butterfly wings with obvious bite marks",
    "Feathers have eye-like markings",
    "Tail ends in a large bow of fur",
    "Tail has bells attached",
    "Tail has jewellery pierced through it",
    "Tail ends in a hand",
    "Tail splits into two at the end",
    "Tail has a tuft that looks suspiciously like a hairstyle",
    "Tail is braided",
    "Their tail wears a tiny bracelet",
    "A halo",
    "A cracked halo",
    "A halo that is far too large",
    "Several tiny halos",
    "Halo sits around their neck instead",
    "Halo floats vertically behind their head",
    "A floating crown that never touches their head",
    "Floating gemstones orbit their head",
    "Floating shards of glass orbit their body",
    "A permanent ring of tiny stars around them",
    "A tiny rain cloud floating over their head",
    "A miniature moon orbiting them",
    "A visible keyhole somewhere on their body",
    "A wind-up key sticking out of their back",
    "Visible puppet joints",
    "Visible strings disappearing upwards",
    "Porcelain ball joints",
    "Hinged jaw like a puppet",
    "A zipper running down their back",
    "Decorative stitching around the edges of their body",
    "A little door in their chest",
    "A glass window in their torso",
    "Ribcage visible through transparent skin",
    "A glowing object visible inside their chest",
    "A tiny ecosystem visible inside their transparent belly",
    "Fish swimming inside them",
    "Their hair contains tiny stars",
    "Hair floats as though underwater",
    "Hair turns into smoke at the ends",
    "Hair turns into leaves at the ends",
    "Hair is actually feathers",
    "Hair is actually tentacles",
    "Hair is actually tiny hands",
    "One extremely long braid reaching the floor",
    "One ridiculous cowlick that defies gravity",
    "A completely inexplicable handle",
    "A price tag they apparently cannot remove",
    "A manufacturer's stamp somewhere on their body",
    "A little maker's signature on their cheek",
    "A barcode",
    "A pull-cord hanging from their back",
    "A large decorative bow somewhere wildly inappropriate",
    "One completely ordinary human hand despite everything else",
    "One completely ordinary human foot despite everything else",
    "A tiny version of themselves sitting on their shoulder",
    "A second, much smaller face that looks deeply unimpressed",
    "One visual feature the artist must add without explaining it"
  ],

  // ============================================================
  // ARTIST POSE SITUATION
  // Add new results by copying a line and changing the text.
  // IMPORTANT: every result except the last one needs a comma.
  // ============================================================
  pose: [
    "Neutral character turnaround",
    "Classic contrapposto",
    "Hands on hips",
    "Arms crossed",
    "Looking over their shoulder",
    "Mid-stride",
    "Running",
    "Crouched",
    "Kneeling",
    "Sitting cross-legged",
    "Sitting backwards on a chair",
    "Perched on something",
    "Leaning against a wall",
    "Leaning against their weapon",
    "Weapon over shoulder",
    "Dramatic spellcasting",
    "Mid-fight",
    "Mid-dance",
    "Mid-laugh",
    "Fixing their hair",
    "Adjusting jewellery",
    "Drinking tea",
    "Eating something",
    "Reading",
    "Sleeping",
    "Sprawled across a throne",
    "Lounging like a Renaissance painting",
    "Heroic low-angle pose",
    "Villainous high-angle pose",
    "Walking away but looking back",
    "Reaching towards the viewer",
    "Holding something tiny very carefully",
    "Holding something enormous very casually",
    "Carrying another character",
    "Princess carry",
    "Sitting like they have never seen a chair before",
    "Awkward school-photo pose",
    "Trying far too hard to look sexy",
    "Accidentally looking sexy",
    "Vogue cover",
    "Mugshot",
    "Family portrait pose despite being alone",
    "Renaissance saint pose",
    "Victorian mourning portrait",
    "Anime protagonist stance",
    "Gremlin crouch",
    "T-posing threateningly",
    "Lying face-down on the floor",
    "Falling down the stairs",
    "Running away from something outside the frame",
    "Pointing dramatically at absolutely nothing",
    "Artist's problem. Good luck."
  ]
};

// ===============================================================
// CATEGORY ORDER / DISPLAY NAMES
// You normally do not need to edit this section.
// ===============================================================

const fields = [
  ["baseForm", "Base Form"],
  ["size", "Size"],
  ["eyes", "How Many Eyes?"],
  ["arms", "How Many Arms?"],
  ["legs", "How Many Legs?"],
  ["handsFeet", "Hands & Feet Situation"],
  ["tail", "Tail Situation"],
  ["skin", "Skin Situation"],
  ["extras", "Horns, Wings & Teeth?"],
  ["fashion", "Fashion Style"],
  ["accessories", "Accessories"],
  ["personality", "Personality Vibe"],
  ["attractiveness", "How Attractive Are They Supposed to Be?"],
  ["romantasy", "Would They Be the Lead in a Romantasy?"],
  ["finalDetail", "Final Questionable Detail"],
  ["pose", "Artist Pose Situation"]
];
